# Generated by Django 5.1 on 2024-08-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0003_rename_año_publicacion_libro_anno_publicacion_and_more'),
    ]

    operations = [
       
       
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
